version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./backend/.env.docker
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend-server
    restart: always
    env_file:
      - ./backend/.env.docker
    ports:
      - "5010:5000"
    depends_on:
      db:
        condition: service_healthy
    command: bash wait-for-it.sh db:3306 -- node server.js
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://188.165.238.74:5010/api
    container_name: frontend-client
    restart: always
    ports:
      - "3010:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://188.165.238.74:5010/api

volumes:
  mysql-data:
