version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./backend/.env.docker
    environment:
      MYSQL_ROOT_PASSWORD: Ilovenaib12!!
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    container_name: backend-server
    restart: always
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db:3306", "--", "node", "server.js"]
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  mysql-data:
