name: Jest & Node16 Compatibility

on:
  push:
  pull_request:

jobs:
  unit-tests-node20:
    name: Unit tests (Jest) on Node 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install root dev deps (Jest etc.)
        run: npm ci

      - name: Install backend deps
        run: npm ci --prefix backend

      # Frontend not needed for unit tests  skipping for speed

      - name: Run Jest
        run: npm test --silent

  install-check-node16:
    name: Install check on Node 16 (no Jest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 16
        uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          cache: "npm"

      # Avoid installing devDependencies at root to skip Jest 30 on Node 16
      - name: Root install (prod only)
        run: npm ci --omit=dev

      - name: Backend install (prod only)
        run: npm ci --omit=dev --prefix backend

      # Frontend deps (CRA supports Node 16). If it ever fails, we can also do --omit=dev here.
      - name: Frontend install
        run: npm ci --prefix frontend
